language: minimal
services: docker
env:
  - image=perl:5.8
  - image=perl:5.10
  - image=perl:5.16
  - image=perl:5.30
before_install:
  - docker pull $image
  - docker run $image perl -V
script:
  - |
    docker run --init -it -v $PWD:/$TRAVIS_REPO_SLUG -w /$TRAVIS_REPO_SLUG $image bash -c '
    set -euxo pipefail
    curl -fsSL --compressed https://git.io/cpm | perl - install -g --show-build-log-on-failure
    prove -lr t
    '
